version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    privileged: true

  frontend:
    image: prog-tt-web:0.0.0
    privileged: true
    environment:
      BACKEND_URI: "http://localhost:3001/query"


  backend:
    image: prog-tt-gql:0.0.0
    privileged: true
    depends_on:
      - db
    environment:
      SQLX_CONN_STRING: "host=db port=5432 user=proglv password=proglv dbname=proglv sslmode=disable"

  db:
    image: postgres
    privileged: true
    environment:
      POSTGRES_USER: proglv
      POSTGRES_PASSWORD: proglv
      POSTGRES_DB: proglv
    ports:
      - "5433:5432"
    volumes:
      - prog_tt_postgres_data:/var/lib/postgresql/data

networks:
  default:
    name: web
    external: true

volumes:
  prog_tt_postgres_data: