apiVersion: apps/v1
kind: Deployment
metadata:
  name: iemacies-prezentacija
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iemacies-prezentacija
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: iemacies-prezentacija
    spec:
      containers:
      - name: iemacies-prezentacija
        image: krisjanisp/iemacieslv-prezentacija:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000  # Changed to 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iemacies-prezentacija
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  tls:
  - hosts:
    - prezentacija.iemacies.lv
    secretName: letsencrypt-nginx-iemacies-prezentacija
  rules:
  - host: prezentacija.iemacies.lv
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iemacies-prezentacija
            port:
              number: 80  # Service port remains 80 for external traffic
  ingressClassName: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: iemacies-prezentacija
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000  # Changed to 8000
  selector:
    app: iemacies-prezentacija
  type: ClusterIP
