apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: proglv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krisjanisp/proglv-backend:latest
          env:
            - name: SQLX_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_CONN_STRING
            - name: AMQP_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: rmq-connection
                  key: RMQ_CONN_STRING
            - name: REDIS_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: REDIS_CONN_STRING
          ports:
            - name: http
              containerPort: 3001
