apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: resource-limits
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 200m
      memory: 400Mi