apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: proglv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          image: krisjanisp/proglv-docs:latest
          ports:
            - name: http
              containerPort: 80
