apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          image: __IMAGE_AUTHOR__/__IMAGE_NAME__:__IMAGE_TAG__
          ports:
            - name: http
              containerPort: 80
