apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-docs
  namespace: backend
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
spec:
  tls:
    - hosts:
      - docs.programme.lv
      secretName: letsencrypt-nginx-docs
  rules:
    - host: docs.programme.lv
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  number: 80
  ingressClassName: nginx 
