apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: 'programme.lv'
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: letsencrypt-nginx-proglv
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: programme-http-redirect
spec:
  parentRefs:
  - name: eg
    namespace: default
    sectionName: http
  hostnames:
    - "programme.lv"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: programme-frontend-route
  namespace: proglv
  labels:
    gateway: programme-gateway
spec:
  parentRefs:
  - name: eg
    namespace: default
    sectionName: https
  hostnames:
    - "programme.lv"
  rules:
    - backendRefs:
      - name: frontend 
        port: 80

